export const categories = [
  "Festival, Fair, Bazaar",
  "Concert",
  "Competition",
  "Exhibition, Expo, Show",
  "Conference",
  "Art, Culture",
  "Workshop",
  "Performance",
  "Attraction, Theme Park",
  "Accommodation",
  "Seminar, Talk Show",
  "Social Gathering",
  "Training, Certification, Exam",
  "School Event",
  "Trip, Tour",
  "Tournament, Competition",
  "Other",
];
