export const topics = [
  "Family, Children",
  "Business",
  "Design, Photo, Video",
  "Fashion, Beauty",
  "Film, Cinema",
  "Game, E-Sports",
  "Hobbies, Crafts",
  "Investment, Stocks",
  "Career, Self Development",
  "Religion",
  "Health, Fitness",
  "Finance, Financial",
  "Environment",
  "Food, Beverage",
  "Marketing",
  "Music",
  "Sports",
  "Automotive",
  "Science, Technology",
  "Art, Culture",
  "Social, Law, Politics",
  "Standup Comedy",
  "Education, Scholarship",
  "Tech, Start-Up",
  "Travel & Vacation",
  "Other",
];
